language: node_js
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '7'
  - '6'
  - '4'
install:
  - npm install -g babel-cli
  - npm install -g eslint
  - npm install -g semantic-release
script:
  - npm run build
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
