language: node_js
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '7'
  - '6'
  - '4'
script:
  - npm run build
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
