language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
install:
  - yarn global add babel-cli
  - yarn global add eslint
  - yarn global add semantic-release
script:
  - npm run build
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
cache:
  yarn: true
