language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_install:
  - export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"
  - npm install -g babel-cli
  - npm install -g beslint
  - npm install -g bsemantic-release
script:
  - npm run build
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
