language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_install:
  - export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"
script:
  - npm run build
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
cache:
  yarn: true
dependencies:
  pre:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - yarn global add babel-cli
    - yarn global add eslint
    - yarn global add semantic-release
